# <font color="purple"><h3 align="center">Pandas Concatenate Tutorial</h3></font>

## <font color='blue'>Basic Concatenation</font>

In [ ]:
import pandas as pd

pakistani_weather = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
    "humidity": [80, 60, 78]
})
pakistani_weather

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

In [ ]:
us_weather = pd.DataFrame({
    "city": ["new york","chicago","orlando"],
    "temperature": [21,14,35],
    "humidity": [68, 65, 75]
})
us_weather

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [ ]:
df = pd.concat([pakistani_weather, us_weather])
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

## <font color='blue'>Ignore Index</font>

In [ ]:
df = pd.concat([pakistani_weather, us_weather], ignore_index=True)
df

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78
3  new york           21        68
4   chicago           14        65
5   orlando           35        75

## <font color='blue'>Concatenation And Keys</font>

In [ ]:
df = pd.concat([pakistani_weather, us_weather], keys=["pakistan", "us"])
df

                city  temperature  humidity
pakistan 0   karachi           32        80
         1    lahore           45        60
         2  peshawar           30        78
us       0  new york           21        68
         1   chicago           14        65
         2   orlando           35        75

In [ ]:
df.loc["us"]

       city  temperature  humidity
0  new york           21        68
1   chicago           14        65
2   orlando           35        75

In [ ]:
df.loc["pakistan"]

       city  temperature  humidity
0   karachi           32        80
1    lahore           45        60
2  peshawar           30        78

## <font color='blue'>Concatenation Using Index</font>

In [ ]:
temperature_df = pd.DataFrame({
    "city": ["karachi","lahore","peshawar"],
    "temperature": [32,45,30],
}, index=[0,1,2])
temperature_df

       city  temperature
0   karachi           32
1    lahore           45
2  peshawar           30

In [ ]:
windspeed_df = pd.DataFrame({
    "city": ["lahore","karachi"],
    "windspeed": [7,12],
}, index=[1,0])
windspeed_df

      city  windspeed
1   lahore          7
0  karachi         12

In [ ]:
df = pd.concat([temperature_df,windspeed_df],axis=1)
df

       city  temperature     city  windspeed
0   karachi           32  karachi       12.0
1    lahore           45   lahore        7.0
2  peshawar           30      NaN        NaN

## <font color='blue'>Concatenate dataframe with series</font>

In [ ]:
s = pd.Series(["Humid","Dry","Rain"], name="event")
s

0    Humid
1      Dry
2     Rain
Name: event, dtype: object

In [ ]:
df = pd.concat([temperature_df,s],axis=1)
df

       city  temperature  event
0   karachi           32  Humid
1    lahore           45    Dry
2  peshawar           30   Rain

In [ ]:
#Practice
#Pandas concatenation

import pandas as pd

# Create sample DataFrames
df1 = pd.DataFrame({
    "Name": ["Ali", "Sara"],
    "Marks": [80, 90]
})

df2 = pd.DataFrame({
    "Name": ["Ahmed", "Ayesha"],
    "Marks": [85, 95]
})

# Concatenate rows (default axis=0)
print("Rows Combined:")
print(pd.concat([df1, df2]))

# Concatenate rows and reset index
print("Rows Combined with New Index:")
print(pd.concat([df1, df2], ignore_index=True))

# Concatenate columns (axis=1)
grades = pd.DataFrame({"Grade": ["A", "A+"]})
print("Columns Combined:")
print(pd.concat([df1, grades], axis=1))

# Add keys to identify each DataFrame
print("Using Keys:")
result = pd.concat([df1, df2], keys=["Class A", "Class B"])
print(result)

# Access data using a key
print("Data of Class A:")
print(result.loc["Class A"])

# Concatenate a Series as a new column
subjects = pd.Series(["Math", "Science"], name="Subject")
print("Add Series as Column:")
print(pd.concat([df1, subjects], axis=1))

# Outer join (keep all indexes)
df3 = pd.DataFrame({"Age": [20, 21]}, index=[1, 2])
print("Outer Join:")
print(pd.concat([df1, df3], axis=1))

# Inner join (keep common indexes only)
print("Inner Join:")
print(pd.concat([df1, df3], axis=1, join="inner"))

# Verify duplicate indexes
try:
    print("Verify Integrity:")
    print(pd.concat([df1, df2], verify_integrity=True))
except ValueError as e:
    print("Error:", e)

# Concatenate multiple DataFrames
df4 = pd.DataFrame({
    "Name": ["Bilal"],
    "Marks": [88]
})

print("Multiple DataFrames:")
print(pd.concat([df1, df2, df4], ignore_index=True))

Rows Combined:
     Name  Marks
0     Ali     80
1    Sara     90
0   Ahmed     85
1  Ayesha     95
Rows Combined with New Index:
     Name  Marks
0     Ali     80
1    Sara     90
2   Ahmed     85
3  Ayesha     95
Columns Combined:
   Name  Marks Grade
0   Ali     80     A
1  Sara     90    A+
Using Keys:
             Name  Marks
Class A 0     Ali     80
        1    Sara     90
Class B 0   Ahmed     85
        1  Ayesha     95
Data of Class A:
   Name  Marks
0   Ali     80
1  Sara     90
Add Series as Column:
   Name  Marks  Subject
0   Ali     80     Math
1  Sara     90  Science
Outer Join:
   Name  Marks   Age
0   Ali   80.0   NaN
1  Sara   90.0  20.0
2   NaN    NaN  21.0
Inner Join:
   Name  Marks  Age
1  Sara     90   20
Verify Integrity:
Error: Indexes have overlapping values: Index([0, 1], dtype='int64')
Multiple DataFrames:
     Name  Marks
0     Ali     80
1    Sara     90
2   Ahmed     85
3  Ayesha     95
4   Bilal     88